import { FasApplicationFilterSection } from '@/features/financial-assistance/components/FasFilterSections'
import { FasAdminApplicationTableSection } from '@/features/financial-assistance/components/FasTableSections'
import { FAS_APPLICATION_STATUS } from '@/features/financial-assistance/data/fasSeedData'
import {
  fasMockStore,
  useFasMockStore,
} from '@/features/financial-assistance/data/fasMockStore'
import { useFasMockTable } from '@/features/financial-assistance/hooks/useFasMockTable'
import '@/features/financial-assistance/styles/financialAssistance.css'
import {
  describeTierSubsidy,
  formatTierConditionText,
  formatFasDate,
  getApplicationDisplayStatus,
  getSuggestedTier,
  isApprovedApplicationExpired,
  statusLabel,
} from '@/features/financial-assistance/utils/fasRules'
import {
  defaultFasApplicationFilters,
  fasApplicationStatusOptions,
} from '@/features/financial-assistance/utils/fasTableConfig'
import { GenericTablePagination } from '@/shared/components/generals/GenericPagination'
import { Button, Card, Flex, Input, Modal, Radio, Select, Tabs, Tag, Typography, message } from 'antd'
import { useEffect, useMemo, useState } from 'react'

const escapePdfText = (value) =>
  String(value || '-')
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')

const createMockDocumentPdfUrl = ({ document, application, scheme, attachment }) => {
  const lines = [
    'Mock supporting document preview',
    `Application: ${application.id}`,
    `Student: ${application.applicantName} (${application.accountNumber})`,
    `Scheme: ${scheme.name}`,
    `Document: ${document.name}`,
    `Uploaded file: ${attachment?.fileName || 'Not attached'}`,
    `Submitted: ${formatFasDate(application.submittedAt)}`,
    '',
    'This PDF is generated by the frontend mock until the real document API is available.',
  ]

  const content = [
    'BT',
    '/F1 18 Tf',
    '72 744 Td',
    `(${escapePdfText(document.name)}) Tj`,
    '/F1 11 Tf',
    ...lines.map((line, index) => `${index === 0 ? '0 -34 Td' : '0 -18 Td'} (${escapePdfText(line)}) Tj`),
    'ET',
  ].join('\n')

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj',
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
    `5 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj`,
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((object) => {
    offsets.push(pdf.length)
    pdf += `${object}\n`
  })

  const xrefOffset = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return URL.createObjectURL(new Blob([pdf], { type: 'application/pdf' }))
}

const FasApplicationQueuePage = () => {
  const { schemes, applications } = useFasMockStore()
  const [filters, setFilters] = useState(defaultFasApplicationFilters)
  const [activeStatus, setActiveStatus] = useState(fasApplicationStatusOptions[0].value)
  const [sort, setSort] = useState({ key: 'submittedAt', direction: 'asc' })
  const [sortChoice, setSortChoice] = useState('oldest')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [reviewId, setReviewId] = useState(null)

  const schemeById = useMemo(
    () => Object.fromEntries(schemes.map((scheme) => [scheme.id, scheme])),
    [schemes]
  )

  const applicationRows = useMemo(
    () =>
      applications
        .map((application) => {
          const scheme = schemeById[application.schemeId]
          if (!scheme) return null

          return {
            ...application,
            schemeName: scheme.name,
            displayStatus: getApplicationDisplayStatus(application),
          }
        })
        .filter(Boolean),
    [applications, schemeById]
  )

  const statusCounts = useMemo(
    () =>
      applicationRows.reduce((acc, application) => {
        acc[application.displayStatus] = (acc[application.displayStatus] || 0) + 1
        return acc
      }, {}),
    [applicationRows]
  )

  const tableData = useFasMockTable({
    rows: applicationRows,
    filters,
    sort,
    page,
    pageSize,
    filterRow: (application, currentFilters) => {
      const query = currentFilters.search.trim().toLowerCase()
      const submittedAt = application.submittedAt || ''
      const matchesQuery =
        !query ||
        application.id.toLowerCase().includes(query) ||
        application.accountNumber.toLowerCase().includes(query) ||
        application.applicantName.toLowerCase().includes(query) ||
        application.schemeName.toLowerCase().includes(query)
      const matchesStatus = application.displayStatus === activeStatus
      const matchesDateFrom = !currentFilters.dateFrom || submittedAt >= currentFilters.dateFrom
      const matchesDateTo = !currentFilters.dateTo || submittedAt <= currentFilters.dateTo

      return matchesQuery && matchesStatus && matchesDateFrom && matchesDateTo
    },
  })

  const reviewApplication = applications.find((application) => application.id === reviewId)
  const reviewScheme = schemeById[reviewApplication?.schemeId]

  const handleFilter = (values) => {
    setFilters(values)
    setPage(1)
  }

  const updateSortChoice = (value) => {
    setSortChoice(value)
    setSort({ key: 'submittedAt', direction: value === 'newest' ? 'desc' : 'asc' })
    setPage(1)
  }

  return (
    <div className="fas-management-shell">
      <Card>
        <Flex vertical gap={16}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            FAS Applications
          </Typography.Title>
          <Tabs
            activeKey={activeStatus}
            onChange={(status) => {
              setActiveStatus(status)
              setPage(1)
            }}
            items={fasApplicationStatusOptions.map((status) => ({
              key: status.value,
              label: `${status.label} (${statusCounts[status.value] || 0})`,
            }))}
          />
          <FasApplicationFilterSection
            filters={filters}
            loading={false}
            searchTitle="Search account, name, FAS, or app no."
            dateTitle="Submitted date"
            showStatus={false}
            onFilter={handleFilter}
            onReset={() => handleFilter(defaultFasApplicationFilters)}
          />
          <Flex justify="end">
            <Select
              value={sortChoice}
              placeholder="Select sort order"
              style={{ width: 180 }}
              options={[
                { value: 'oldest', label: 'Oldest first' },
                { value: 'newest', label: 'Newest first' },
              ]}
              onChange={updateSortChoice}
            />
          </Flex>
          <FasAdminApplicationTableSection
            applications={tableData.collection}
            loading={false}
            sort={sort}
            setSort={setSort}
            onReview={(application) => setReviewId(application.id)}
          />
          <GenericTablePagination
            totalCount={tableData.totalCount}
            totalPage={tableData.totalPage}
            page={page}
            setPage={setPage}
            pageSize={pageSize}
            setPageSize={setPageSize}
            loading={false}
          />

          <div className="fas-note">
            <strong>Review rule:</strong> Pending applications are decided one at a time. The tier is
            selected by the system from the scheme rules and student data.
          </div>
        </Flex>
      </Card>

      <ApplicationReviewModal
        application={reviewApplication}
        scheme={reviewScheme}
        open={!!reviewApplication && !!reviewScheme}
        onClose={() => setReviewId(null)}
      />
    </div>
  )
}

const ApplicationReviewModal = ({ application, scheme, open, onClose }) => {
  const [rejectOpen, setRejectOpen] = useState(false)
  const [reason, setReason] = useState('')
  const [overrideReason, setOverrideReason] = useState('')
  const [documentPreview, setDocumentPreview] = useState(null)
  const suggestedTier = getSuggestedTier(scheme, application)
  const defaultTierId = suggestedTier?.id || scheme?.tiers?.[0]?.id || null
  const [manualTierSelection, setManualTierSelection] = useState({
    applicationId: null,
    tierId: null,
  })
  const selectedTierId =
    manualTierSelection.applicationId === application?.id
      ? manualTierSelection.tierId
      : defaultTierId
  const selectedTier = scheme?.tiers?.find((tier) => tier.id === selectedTierId)
  const needsOverrideReason = !!selectedTier && selectedTier.id !== suggestedTier?.id
  const expired = isApprovedApplicationExpired(application)

  useEffect(() => {
    if (!documentPreview?.url) return undefined

    return () => URL.revokeObjectURL(documentPreview.url)
  }, [documentPreview?.url])

  const selectTier = (tierId) => {
    setManualTierSelection({ applicationId: application?.id, tierId })
  }

  const close = () => {
    setRejectOpen(false)
    setReason('')
    setOverrideReason('')
    setDocumentPreview(null)
    setManualTierSelection({ applicationId: null, tierId: null })
    onClose()
  }

  const viewDocument = (document) => {
    const attachment = application.attachments?.find((item) => item.documentId === document.id)
    if (!attachment) {
      message.warning('Document is missing')
      return
    }

    setDocumentPreview((current) => {
      if (current?.url) URL.revokeObjectURL(current.url)
      return {
        title: document.name,
        url: createMockDocumentPdfUrl({ document, application, scheme, attachment }),
      }
    })
  }

  const approve = () => {
    if (!selectedTier) return

    if (needsOverrideReason && !overrideReason.trim()) {
      message.error('Enter the reason for overriding the recommended tier')
      return
    }

    fasMockStore.approveApplication(application.id, selectedTier.id, {
      recommendedTierId: suggestedTier?.id,
      reason: needsOverrideReason
        ? overrideReason.trim()
        : 'Approved the system-recommended tier.',
    })
    message.success(`Approved ${application.id} · ${selectedTier.name}`)
    close()
  }

  const reject = () => {
    if (!reason.trim()) {
      message.error('Enter a rejection reason')
      return
    }

    fasMockStore.rejectApplication(application.id, reason.trim())
    message.success(`Rejected ${application.id}`)
    close()
  }

  if (!application || !scheme) return null

  const title = `${application.status === FAS_APPLICATION_STATUS.Pending ? 'Review' : 'View'} · ${
    application.id
  }`

  return (
    <Modal title={title} open={open} onCancel={close} footer={null} width={620}>
      {application.status === FAS_APPLICATION_STATUS.Pending ? (
        <>
          <StudentDataBlock application={application} scheme={scheme} />

          <div className="fas-section-label" style={{ marginBottom: 7 }}>
            Tier selection
          </div>
          <TierTable
            scheme={scheme}
            selectedTierId={selectedTierId}
            systemTierId={suggestedTier?.id}
            onSelectTier={selectTier}
          />

          {suggestedTier && selectedTier?.id === suggestedTier.id ? (
            <div className="fas-suggest">
              System recommended <strong>{suggestedTier.name}</strong> from the student data.
            </div>
          ) : suggestedTier && selectedTier ? (
            <div className="fas-suggest">
              System recommended <strong>{suggestedTier.name}</strong>, but{' '}
              <strong>{selectedTier.name}</strong> is selected for approval.
            </div>
          ) : selectedTier ? (
            <div className="fas-suggest">
              No exact tier matched the student data. <strong>{selectedTier.name}</strong> is
              selected manually.
            </div>
          ) : (
            <div className="fas-suggest fas-suggest-danger">
              No tier is available. Approve is disabled.
            </div>
          )}

          {needsOverrideReason && (
            <div style={{ marginBottom: 12 }}>
              <label className="fas-field-label">Override reason</label>
              <Input.TextArea
                value={overrideReason}
                rows={3}
                placeholder="Reason for selecting a different tier"
                onChange={(event) => setOverrideReason(event.target.value)}
              />
            </div>
          )}

          <RequiredDocuments scheme={scheme} application={application} onView={viewDocument} />

          <Flex gap={8} style={{ marginTop: 14 }}>
            <Button type="primary" disabled={!selectedTier} style={{ flex: 1 }} onClick={approve}>
              {selectedTier ? `Approve · ${selectedTier.name}` : 'Approve'}
            </Button>
            <Button danger style={{ flex: 1 }} onClick={() => setRejectOpen(true)}>
              Reject
            </Button>
          </Flex>

          {rejectOpen && (
            <div style={{ marginTop: 12 }}>
              <Input.TextArea
                value={reason}
                rows={3}
                placeholder="Reason, e.g. Income documents incomplete"
                onChange={(event) => setReason(event.target.value)}
              />
              <Flex gap={8} style={{ marginTop: 8 }}>
                <Button danger type="primary" onClick={reject}>
                  Confirm reject
                </Button>
                <Button onClick={() => setRejectOpen(false)}>Cancel</Button>
              </Flex>
            </div>
          )}
        </>
      ) : (
        <>
          <div className="fas-kv">
            <div className="fas-kv-row">
              <span>Student</span>
              <strong>
                {application.applicantName} · {application.accountNumber}
              </strong>
            </div>
            <div className="fas-kv-row">
              <span>Scheme</span>
              <strong>{scheme.name}</strong>
            </div>
            <div className="fas-kv-row">
              <span>Result</span>
              <strong style={{ color: expired ? 'var(--fas-red)' : 'var(--fas-green)' }}>
                {expired ? 'Expired' : statusLabel(application.status)}
                {application.tierId ? ` · ${scheme.tiers.find((t) => t.id === application.tierId)?.name}` : ''}
              </strong>
            </div>
            {application.validFrom && (
              <div className="fas-kv-row">
                <span>Valid from</span>
                <strong>{formatFasDate(application.validFrom)}</strong>
              </div>
            )}
            <div className="fas-kv-row">
              <span>Duration</span>
              <strong>{scheme.validityMonths || 12} months</strong>
            </div>
            {application.endDate && (
              <div className="fas-kv-row">
                <span>Valid until</span>
                <strong style={{ color: expired ? 'var(--fas-red)' : undefined }}>
                  {formatFasDate(application.endDate)}
                  {expired ? ' · Expired' : ''}
                </strong>
              </div>
            )}
            {application.status === FAS_APPLICATION_STATUS.Rejected && (
              <div className="fas-kv-row">
                <span>Reason</span>
                <strong>{application.reason || '-'}</strong>
              </div>
            )}
            {application.status === FAS_APPLICATION_STATUS.Approved && application.tierReview && (
              <>
                <div className="fas-kv-row">
                  <span>Approved reason</span>
                  <strong>{application.tierReview.reason || '-'}</strong>
                </div>
                <div className="fas-kv-row">
                  <span>Approved by</span>
                  <strong>{application.tierReview.modifiedBy || '-'}</strong>
                </div>
                <div className="fas-kv-row">
                  <span>Approved date</span>
                  <strong>{formatFasDate(application.tierReview.modifiedDate?.slice(0, 10))}</strong>
                </div>
              </>
            )}
          </div>
          <StudentDataBlock application={application} scheme={scheme} />
          <RequiredDocuments scheme={scheme} application={application} onView={viewDocument} />
        </>
      )}
      <DocumentPreviewModal
        open={!!documentPreview}
        title={documentPreview?.title}
        url={documentPreview?.url}
        onClose={() => setDocumentPreview(null)}
      />
    </Modal>
  )
}

const StudentDataBlock = ({ application }) => (
  <div className="fas-kv">
    <div className="fas-kv-row">
      <span>Student age</span>
      <strong>{application.data?.age || '-'}</strong>
    </div>
    <div className="fas-kv-row">
      <span>Student nationality</span>
      <strong>{application.data?.nationality || '-'}</strong>
    </div>
    <div className="fas-kv-row">
      <span>Parent nationality</span>
      <strong>{application.data?.parentNationality || '-'}</strong>
    </div>
    <div className="fas-kv-row">
      <span>Gross household income</span>
      <strong>S${Number(application.data?.income || 0).toLocaleString()}</strong>
    </div>
    <div className="fas-kv-row">
      <span>Members</span>
      <strong>{application.data?.members || '-'}</strong>
    </div>
    <div className="fas-kv-row">
      <span>Per-capita income (PCI)</span>
      <strong>S${Number(application.data?.pci || 0).toLocaleString()}</strong>
    </div>
  </div>
)

const TierTable = ({ scheme, selectedTierId, systemTierId, onSelectTier }) => (
  <table className="fas-tier-table">
    <thead>
      <tr>
        <th>Tier</th>
        <th>Condition</th>
        <th>Subsidy</th>
      </tr>
    </thead>
    <tbody>
      {scheme.tiers.map((tier) => {
        const isSelected = tier.id === selectedTierId
        const isSystemTier = tier.id === systemTierId

        return (
        <tr
          key={tier.id}
          className={`${isSelected ? 'is-selected' : ''} ${
            isSystemTier ? 'is-system-tier' : ''
          }`.trim()}
          onClick={() => onSelectTier?.(tier.id)}
        >
          <td>
            <Radio checked={isSelected} onChange={() => onSelectTier?.(tier.id)}>
              {tier.name}
              {isSystemTier ? ' · recommended' : ''}
            </Radio>
          </td>
          <td>{formatTierConditionText(tier)}</td>
          <td>{describeTierSubsidy(scheme, tier)}</td>
        </tr>
        )
      })}
    </tbody>
  </table>
)

const RequiredDocuments = ({ scheme, application, onView }) => (
  <div>
    <div className="fas-section-label" style={{ marginBottom: 7 }}>
      Supporting documents to verify
    </div>
    <Flex gap={6} wrap="wrap">
      {scheme.documents.length ? (
        scheme.documents.map((document) => {
          const attached = application.attachments?.some((item) => item.documentId === document.id)
          return (
            <Tag
              color={attached ? 'blue' : 'default'}
              key={document.id}
              style={{ cursor: attached ? 'pointer' : 'default' }}
              onClick={() => {
                if (attached) onView?.(document)
              }}
            >
              {document.name} · {attached ? 'View PDF' : 'Missing'}
            </Tag>
          )
        })
      ) : (
        <span className="fas-muted">No documents required</span>
      )}
    </Flex>
  </div>
)

const DocumentPreviewModal = ({ open, title, url, onClose }) => (
  <Modal title={title || 'Document preview'} open={open} onCancel={onClose} footer={null} width={840}>
    {url ? (
      <iframe
        title={title || 'Document preview'}
        src={url}
        style={{ width: '100%', height: '72vh', border: 0, borderRadius: 8 }}
      />
    ) : (
      <span className="fas-muted">No document available.</span>
    )}
  </Modal>
)

export default FasApplicationQueuePage
